### ISSUE TITLE
Finish config file module

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#1]
A config module is started. However, given the changes in the config file structure it may or may not be as useful as planned. The current implementation takes a yaml file and turns it into a class instance with dot notation. It also accepts default values from plugins. With more complex billing  data in config it may not be as useful to use dot notation as it may be more intuitive to have a dictionary. Such as to find a specific billing type using a key rather than iteration or `getattr`.

- Decide on final architecture for class
- Cleanup code and add fault tolerance
- Add tests
- Integration testing

https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/devel/csp_billing_adapter/config.py

**Comment by smarlowucf** [comment]
Note: if we revert to a dictionary instead of a class this needs to be coordinated. As all plugins and hooks reference a class in type hints.

**Comment by KeithMnemonic** [comment]
@smarlowucf  If I take you existing code, but have Config inherit from a dict, I can access members via lookup and dot notation. Would this be sufficient?

i.e

```
if __name__ == "__main__":

    # Creating the dictionary
    config_data = {"Name": "Billing Test App",
               "Offer": "1234",
               "Dimension": "Hours"}

    result = Config(config_data)

    # printing the result
    print(result.get('Name'))
    print(result.Name)
```

**Comment by smarlowucf** [comment]
Yeah, it's probably okay to have both. The idea for dot notation was when the config file was more flat. config.something config.something_else. And it's probably going to be much more complicated with lists and dicts and list of dicts and dicts of dicts. IMHO it's best to wait for finalization there before we choose a new path.

**Comment by KeithMnemonic** [comment]
> Another note I have in my backlog about config is how we handle no config file. Do we raise an error and treat it as a hard failure or try to move forward with default values.

Right now in hosts.py. you would generate an exception and exit when you call Config.load_from_file().  

Do we want to handle this within config and maybe log an info message saying "No config file specified, falling back to defaults" if a file is not present?

One caveat though, are we storing/referencing the credentials used by the CSP in this file.?  Somehow we need to specify where to find the AWS/Azure/GCP creds.  If we are going to store this reference  (AWS profile name, or location of Azure Service Principal json file) in this file, than it seems the file must exist and if not we should exit with an appropriate error message. 

Also do we want to do schema verification of the config file using cerberus as done in suse-migration-services or pint-data-manager?

**Comment by smarlowucf** [comment]
How we log is TBD. If this runs in a container that lends itself to printing to stdout. But we can setup a logger to handle different environments.

The main event must always run so we have to catch all errors there. Ideally we catch anything expected and handle if possible inside the underlying functions or re-raise a useful error to the main loop. The main loop would go into error state and add the error to csp config map.

There's no credentials handling. Adapter is inside a cloud environment so it will be giving the necessary credentials in the running environment.

My opinion would be no schema verification because the config must be there in practice. We are building the container and the config file is part of the container. If a customer digs in and mucks it up that's not something we can do anything about. I guess that same thought process could go for if config file is missing. But maybe better a bullet point for quick discussion?

**Comment by rjschwei** [comment]
The adapter, by definition, cannot function without a config, what would we report to the CSP API if we have no config? What API would we query to get the data to report if we have no config? No config is a shutdown condition.

**Comment by KeithMnemonic** [comment]
@smarlowucf Why is there no credential handling? From the docs we have so far for the Microsoft Azure Marketplace Metered Billing APIs, they mention needing the following:

```
A unique access token that identifies the ISV that is making this API call. The format is "Bearer <access_token>" when the token value is retrieved by the publisher as explained for
```
so how would we create a token without accessing appropriate credentials?  It seems one option is these credentials are only loaded when a corresponding csp adapter plugin is detected.  Perhaps we setup the Config class to also support plugins. This allows loading any extra settings needed for a particular csp or storage adapter when those are in use.

**Comment by smarlowucf** [comment]
Credentials are provided by the environment and permissions setup by the end user.

**Comment by KeithMnemonic** [comment]
@smarlowucf I am still missing something here. the Azure Metered Billing REST API's mention the need for a Bearer token,  The article mentions ways to authenticate. https://learn.microsoft.com/en-us/partner-center/marketplace/marketplace-metering-service-authentication  "Once you have registered your application, you can programmatically request an Azure AD security token. "  

I am not seeing how this gets done without having the client_id and such.  @rjschwei @bear454 Do you have any experience or comments on this? I.e from within an Azure VM/Container create/retrieve an access token without specifying clientId or such?

**Comment by rtamalin** [comment]
@smarlowucf @rjschwei With regard to config validation, while it may not be _required_ for the actual deployments, because a valid config should exist in the container (or VM) image, might it not be useful to have a config validator mechanism that can be used to validate the configs when they are being generated in the first place, to ensure that the versions that are being embedded in the images are in fact valid?

E.g. something that could potentially be run as of the image build process to catch an invalid config before we even build the image?

**Comment by rjschwei** [comment]
It becomes a test in the package that builds the config rpm and we do a pre-install in the project config of the validataor package and then we can run the command in %check

**Comment by KeithMnemonic** [comment]
@smarlowucf  I spoke with @bear454 amd we reviwed the docs for Managed Applications. It looks like with the proper setup of the managed identity we should be able to get the token from the metadata service.  We will not know for sure until we can deploy a test Packaged Application in Azure and see if the generated token lets us use the Metered Billing Rest APIs.

**Comment by KeithMnemonic** [comment]
closed with pr https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/27 and https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/38
