### ISSUE TITLE
PR for utility functions

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#11]
There exists utility functions around timestamp and relative delta handling. This code should be cleaned up and pushed to main after initial setup PR is merged.

https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/devel/csp_billing_adapter/utils.py

**Comment by smarlowucf** [comment]
I think those functions are good to go. Just need docstrings, tests etc.

**Comment by KeithMnemonic** [comment]
@smarlowucf there is no exception handling. Do you want to add it here or does this get covered somewhere else. Just in case "garbage in" is passed to any of these functions?

**Comment by smarlowucf** [comment]
Yeah, anything that seems necessary in terms of exception handling.

**Comment by KeithMnemonic** [comment]
resolved by https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/44
