### ISSUE TITLE
meter_billing() hook should return a dict mapping metered dimensions to record ids

### ISSUE THREAD

**Issue by rtamalin** [SUSE-Enceladus/csp-billing-adapter#112]
Metering for multiple dimensions, in some cases, may result in multiple submissions to the associated CSP, so we should be returning a list of record ids, rather than just a single record id.

**Comment by smarlowucf** [comment]
Sorry I double checked the aws docs for batch_meter_usage api and it's for saas offerings. This means we have to call meter_usage many times for multiple dimensions. Thus I think we will need this to be a dict return type. Something that maps each meter call dimension to the billing id:

{'dimension_1': '1234567890', 'dimension_2': '987654321'}

This ends up in cache alongside the dimension to quantity map for cross reference.

{'dimension_1': 15, 'dimension_2': 10}

This would provide all the details necessary.
