### ISSUE TITLE
Cleanup billing functions

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#12]
There are functions in progress for calculating usage for billing. These are in progress and need to be finished, cleaned up and organized. Ideally the core algorithms could be organized in one module. If possible leverage pluggy to make things pluggable were it makes sense.

Note this will be affected by changes to the config file structure.

In question:

- get_max_usage
- get_average_usage
- get_billable_usage
- get_bulk_dimensions
- get_billing_dimensions

https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/devel/csp_billing_adapter/csp_cache.py

**Comment by smarlowucf** [comment]
Once cleaned up the same applies: doc strings, unit tests, fault tolerance and etc.

**Comment by smarlowucf** [comment]
We can split up the functions into separate tickets as we pickup them up since they should all be independent to some degree.

**Comment by rjschwei** [comment]
The average calculation uses math.ceil() this may not be what we want. I have started a conversation with PM about the behavior we expect. The current implementation would put a user into the next category along a tiered pricing structure even if the user barely used more then the category, for example if the tier level is 15 and we calculate 15.000000000009 as the average the count would be pushed to the next tier. Making such decisions in code without comment or communication is concerning.

**Comment by rjschwei** [comment]
Always rounding up is OK, confirmed with PM 04/14/23, please make sure there is a comment in the final code.
