### ISSUE TITLE
Log usage records from application API

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#14]
The event loop should run based on the query interval. On every run we get usage from the app api. If there's a new record it gets saved to the cache.

https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/devel/csp_billing_adapter/host.py

**Comment by rjschwei** [comment]
Based on the implementation I don't understand how we would ever bill. The "meter_billing()" call is guarded by a condition where the minutes end with "3", i.e. only adapters that wake up at minute 3, 13, 23, 33, 43, and 53 of the hour would bill. All other adatpers that wake up during the other 54 minutes of the hour would not bill?
