### ISSUE TITLE
Decide how to find the correct product id based on geo

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#15]
There will be two different products in each csp. The product is determined by geo. The adapter will need a way to figure out which of the two products to use based on the current location.

**Comment by rjschwei** [comment]
AFAIK there is no API for container products to get the product ID (AWS terminology) from the framework. Calling metadata API results in data from the underlying instance on which the k8s cluster is running on. We probably want to add this to the csp-adapter config.

**Comment by smarlowucf** [comment]
Yes, the two product id's would go in config. But the question is how does the adapter determine what product id to use in a given deployment?

- Do we configure regions per product? Probabaly not a good idea because regions are always changing.
- Is there a way to search for something whereas we would only get a response for one of the product ids?

?

**Comment by rjschwei** [comment]
We could add `product_code` to the adapter config.

**Comment by smarlowucf** [comment]
This will be in config no code needed. Leaving open for documentation.

**Comment by smarlowucf** [comment]
Captured outside of github.
