### ISSUE TITLE
Update copyright notice in modules (project wide)

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#16]
Some modules have a minimal notice and some have nothing. We should decide on a standard apache 2.0 notice to add to the beginning of modules. This is project wide (core and all plugins).

**Comment by rjschwei** [comment]
The notice is dictated by the license, see https://www.apache.org/licenses/LICENSE-2.0 "HOW TO APPLY THE APACHE LICENSE TO YOUR WORK" every file needs to have that text, no exceptions.

**Comment by rtamalin** [comment]
Proposed:

- SUSE-Enceladus/csp-billing-adapter#22
- SUSE-Enceladus/csp-billing-adapter-amazon#2
- SUSE-Enceladus/csp-billing-adapter-k8s#3
- SUSE-Enceladus/csp-billing-adapter-local#2
- SUSE-Enceladus/csp-billing-adapter-microsoft#2

**Comment by rtamalin** [comment]
@smarlowucf @rjschwei Is what I did here sufficient? Or do we need to add copyrights to more files?

**Comment by rjschwei** [comment]
@rtamalin LGTM

**Comment by rtamalin** [comment]
Ok so we just need to land the versions from the devel branch on the main branch and we can close this issue out.

**Comment by smarlowucf** [comment]
Everything merged to main.
