### ISSUE TITLE
Collect CSP data

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/csp-billing-adapter#20]
Any implementation needs to collect CSP information that is sufficient to meet the requirements that allows SCC to automatically create support cases. 

Suggest to use the commands we use in AMI's we publish to collect metadata as this infrastructure already exists.

**Comment by smarlowucf** [comment]
This can be part of csp hooks which will allow the core code to define a standard interface and return value to ensure csp specific data does not leak into core code.

**Comment by smarlowucf** [comment]
@rjschwei can you provide more details on what needs to be collected?

**Comment by rjschwei** [comment]
We want to run the commands that are configured in the cloud regionsrv-client configuration and the information needs to be included in the suportconfig

**Comment by smarlowucf** [comment]
This is defined. Last step is integrating the function in amazon plugin. Changing tag accordingly.

**Comment by smarlowucf** [comment]
Requirements are missing here. What was communicated is that we need the following fields:

- account_id
- arch
- cloud_provider

It sounds like we also need to include signature/checksum to validate the data which changes the interface again.
