### ISSUE TITLE
yaml package is imported by csp_billing_adapter.config but not specified in requirements

### ISSUE THREAD

**Issue by rtamalin** [SUSE-Enceladus/csp-billing-adapter#23]
Attempting to run `csp-billing-adpater --help` after installing in a venv that was created with `python -m venv venv` failed due to the yaml package not being available in the venv.

Adding `pyyaml` to the requirements.txt should address this.

**Comment by smarlowucf** [comment]
Yeah, I was still probing how to handle config file and thus hadn't gotten to requirements updates. If we stick yaml then we'd need to update spec as well. And I think in PyPI the name is PyYAML. Not sure if case matters but doesn't hurt to match.

**Comment by rjschwei** [comment]
So we have settled on json for the communication with NeuVector, i.e. whet we take in from NeuVector and what they consume from the adapter to generate the support config. While both PyYAML and json are readily available and well maintained upstream do we really need to depend on both and is that really to our advantage?

**Comment by smarlowucf** [comment]
YAML seems more user friendly given the expectation that these will be maintained by non-developers.
