### ISSUE TITLE
Add file based logging handler for vm products

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#33]
Logging is deployment environment specific. There should be a hookspec for retrieving a logger and we could probably log to console by default. This means the local storage plugin implements the hook and sets up some sort of file log.

**Comment by smarlowucf** [comment]
Some of log setup could also be part of config such as log level. That way it could be configurable for test/debug.

**Comment by smarlowucf** [comment]
I don't know if this makes sense as I wrote it. I think we want a way to set log level in config maybe? Then maybe in the setup the logger gets set accordingly. For example when running in a container in k8s we want the logger to be at info level and push logs to console so that they are visible to k8s. In a VM it could be pushed to a log file and either info or warning level.

**Comment by rjschwei** [comment]
How would "override via config" work in a container setting? Is the thought to build all the stuff one needs to connect to a container into the container or are we going for a true application container, i.e. no connection to the container is possible? It is probably a good idea not have the behavior differ between the adapter running in a k8s environment and running possibly as a daemon on a VM.

**Comment by smarlowucf** [comment]
Logging is different in a container in that there's no expectation of container access nor storage. Thus the adapter would print to console. k8s picks up anything printed to console for pod logs such as:

```
> kubectl logs --namespace neuvector-csp-billing-adapter billing-adapter-6866566947-px82h
INFO:CSPBillingAdapter:Mock CSP received metering of: {'tier_1': 0}
```

In a VM there's an assumption of stateful storage and thus the adapter could bump to a log file instead of dumping to console.

**Comment by smarlowucf** [comment]
Not sure how to scope this. For k8s release as long as default logger is setup and logging it goes to the right place and logs end up visible to k8s. So expanding on this is maybe in v2 scope.

**Comment by rjschwei** [comment]
Since there is no "v2" timeline and things getting pushed to that state it is probably a good idea to define what that means. For this issue it would mean before end of July for example as August is the SUMa release target. Other issues labeled as v2 may not fall within that timeline.

**Comment by smarlowucf** [comment]
If we plan to "release" monthly it could be month tags? June, July etc.

**Comment by smarlowucf** [comment]
@jesusbv this is relevant to the logging implementation.

**Comment by smarlowucf** [comment]
Re-name to prevent confusion. The main goal with this ticket was to add a file based handler for VM products. I mistakenly opened the ticket with a solution instead of the problem. The get_logger hookspec was only an idea for solution. There are other possibly much simpler ways to handle this problem.

**Comment by jesusbv** [comment]
Closing this issue as this has been added in #126 and SUSE-Enceladus/csp-billing-adapter-local/pull/12

**Comment by jesusbv** [comment]
Closing this issue as this has been added in #126 and SUSE-Enceladus/csp-billing-adapter-local/pull/12
