### ISSUE TITLE
Decide how to handle the test plugins in core package

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#62]
There are 4 plugins that exist in core code to help assist with development and testing:

- local_csp
- product_api
- memory_cache
- memory_csp_config

These are not intended for production environment. However, they are very useful for testing and development. Thus they should remain in code base but probably should not be loaded by default such as https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/main/csp_billing_adapter/adapter.py#L66.

From a testing perspective they can be loaded such as https://github.com/SUSE-Enceladus/csp-billing-adapter/blob/main/tests/unit/conftest.py#L86. 

For v1 release we can probably just drop the local_csp from core code and move it to the conftest file. Anything else we can probably push to v2 discussion.

**Comment by smarlowucf** [comment]
See https://github.com/SUSE-Enceladus/csp-billing-adapter/pull/60 for context on this issue.

**Comment by smarlowucf** [comment]
I think what's left here is drop `pm.register(local_csp)` from initialization code.

**Comment by rtamalin** [comment]
I think functionally we have completed this task, but I still think we should move the 4 testing support plugins into a subpackage, e.g. testing, under the csp_billing_adapter package, to make it clear that they are not part of the core functionality.

**Comment by rtamalin** [comment]
I think that all the changes we need for June are in place now, so we can either lose this one as complete, or remove the June and add the July label to reflect that we don't need to complete restructuring right now?

**Comment by smarlowucf** [comment]
Yeah, closing is fine. A new bug can be opened if we decide to move the modules later.
