### ISSUE TITLE
Handle no matching dimension in volume pricing

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#63]
In the volume pricing model if a matching dimension is not found an exception needs to be raised and bubbled up to the config map with details on the issue and failed billing state. Since the adapter cannot bill usage if there's not a matching dimension and it shouldn't try to guess at what dimension to bill.

**Comment by rtamalin** [comment]
@smarlowucf I think we can probably close this one?
