### ISSUE TITLE
Only process records in last cycle

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#64]
The billing calculation takes all records in cache into account when processing usage. Instead it should only take records that were created since the last bill time and up to the current bill time.

**Comment by rtamalin** [comment]
Note that with the current code flow the billing period that process_metering() will be targeting is the period ending at the time recorded in the cache's `next_bill_time` entry.

If the adapter hasn't been able to successfully process metering requests for an extended period of time, this may not correspond to/overlap with the "current" billing period... This is something that we likely will want to address as part of #65.

**Comment by smarlowucf** [comment]
Yep, agree :+1:

**Comment by rtamalin** [comment]
Ok closing this one as completed; re-open if needed.
